"""empty message

Revision ID: eab6c382b388
Revises: 
Create Date: 2017-11-13 10:03:18.512910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab6c382b388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('img_url', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('sign_up_url', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_end_date'), 'activities', ['end_date'], unique=False)
    op.create_index(op.f('ix_activities_start_date'), 'activities', ['start_date'], unique=False)
    op.create_index(op.f('ix_activities_timestamp'), 'activities', ['timestamp'], unique=False)
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carousels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_table('friend_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_timestamp'), 'info', ['timestamp'], unique=False)
    op.create_table('many',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], )
    )
    op.create_table('nav_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.Column('abstract', sa.String(length=200), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['nav_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_table('solo',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('maxim', sa.String(length=64), nullable=True),
    sa.Column('about_us', sa.String(length=128), nullable=True),
    sa.Column('emblem_hash', sa.String(length=128), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['captain_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('captain_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('avatar_hash', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('tops', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('qq', sa.Integer(), nullable=True),
    sa.Column('WeChat', sa.String(length=16), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('web_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corporate_name', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone_num', sa.Integer(), nullable=True),
    sa.Column('WeChat', sa.String(length=32), nullable=True),
    sa.Column('WeChat_img', sa.Text(), nullable=True),
    sa.Column('sina_blog', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('contacts', sa.String(length=32), nullable=True),
    sa.Column('qq', sa.String(length=32), nullable=True),
    sa.Column('about_me_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_settings')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('solo')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('nav_settings')
    op.drop_table('many')
    op.drop_index(op.f('ix_info_timestamp'), table_name='info')
    op.drop_table('info')
    op.drop_table('friend_links')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('carousels')
    op.drop_table('administrator')
    op.drop_index(op.f('ix_activities_timestamp'), table_name='activities')
    op.drop_index(op.f('ix_activities_start_date'), table_name='activities')
    op.drop_index(op.f('ix_activities_end_date'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
